### PR TITLE
Translated uk.json to Ukrainian.

### PR DESCRIPTION
**Pull request by DAle-q**
https://docs.google.com/document/d/1KWwudhXqupq1OAQcgLiTwurWsRKCMJBbooodo18gcnc/edit?usp=sharing This is my memo, I'll do it better after sleep.

### CODE REVIEW

**Comment by emielvanderhoek** [comment]
Hi @DAle-q ,
Has the work been completed?

**Comment by DAle-q** [comment]
> Hi @DAle-q ,
> Has the work been completed?
Hi!
Work is done, please ask If you have any questions.

**Comment by DAle-q** [comment]
> Hi @DAle-q ,
> Has the work been completed?

Sorry, if I'm persistent, but any feedback? What to improve?

**Comment by emielvanderhoek** [comment]
Thank you for your efforts @DAle-q 

Would you please be so kind to send me a signed Contributor License Agreement as mentioned in this issue #7 ? You can send that signed document to "emiel AT web3scan DOT eu".

After that I'll ask to get this merged and we can go towards bounty payout.

**Comment by DAle-q** [comment]
Thank you for reply, I signed and sended CLA pdf to emiel AT web3scan DOT eu. I believe nothing wrong.

**Comment by emielvanderhoek** [comment]
> https://docs.google.com/document/d/1KWwudhXqupq1OAQcgLiTwurWsRKCMJBbooodo18gcnc/edit?usp=sharing This is my memo, I'll do it better after sleep.

@DAle-q Could you please add the content of that memo as a comment in this PR?

**Pull request merged**
