### PR TITLE
Add Hindi translation

### PR DESCRIPTION
**Pull request by srisankethu**

### CODE REVIEW

**Comment by srisankethu** [comment]
Made literal language changes. Need to see the structure of the sentence and make suitable changes.

**Comment by emielvanderhoek** [comment]
> With [dc1b0d6](https://github.com/polkascan/polkascan-explorer-gui/commit/dc1b0d6ef6f4b77039f0b088305449eb62af272d), made literal language changes. Need to see the structure of the sentence and make suitable changes.

There are instructions in the issue (https://github.com/polkascan/polkascan-explorer-gui/issues/19) that allow you to run the explorer user-interface yourself. This allows you to check structure of sentences.

**Comment by srisankethu** [comment]
> > With [dc1b0d6](https://github.com/polkascan/polkascan-explorer-gui/commit/dc1b0d6ef6f4b77039f0b088305449eb62af272d), made literal language changes. Need to see the structure of the sentence and make suitable changes.
> 
> There are instructions in the issue (#19) that allow you to run the explorer user-interface yourself. This allows you to check structure of sentences.

I am only getting 4 languages when I followed the instructions!? i.e English, Simplified Chinese, Korean and Russian

**Comment by emielvanderhoek** [comment]
> I am only getting 4 languages when I followed the instructions!? i.e English, Simplified Chinese, Korean and Russian

Ah after checking I can explain this. You made a pull request from/to the master branch of this repo. You should have worked from another branch: `feature/i18n` as specified in the instructions here: https://github.com/polkascan/polkascan-explorer-gui/issues/19

If you follow the instructions on that branch you will see many more languages.

**Comment by srisankethu** [comment]
@emielvanderhoek I have checked the translations. Its seems good to me.

**Comment by emielvanderhoek** [comment]
Thank you for your efforts @srisankethu 

Would you please be so kind to send me a signed Contributor License Agreement as mentioned in this issue #19 ? You can send that signed document to "emiel AT web3scan DOT eu".

After that I'll ask to get this reviewed and merged and we can go towards bounty payout.

**Comment by srisankethu** [comment]
> Thank you for your efforts @srisankethu
> 
> Would you please be so kind to send me a signed Contributor License Agreement as mentioned in this issue #19 ? You can send that signed document to "emiel AT web3scan DOT eu".
> 
> After that I'll ask to get this reviewed and merged and we can go towards bounty payout.

I have sent the Contributor agreement to your email. I see some bounties on Gitcoin for Polkascan.js translation. If you are happy with my work may be I can worked on Hindi translation for Polkascan.js. Thanks.

**Comment by emielvanderhoek** [comment]
Thank you. We will evaluate and merge at our earliest convenience.

**Pull request merged**
