### PR TITLE
Added new Turkish translation

### PR DESCRIPTION
**Pull request by anldrms**
I've updated Turkish translation for Polkascan.
* **Bounty Link:**  https://gitcoin.co/issue/polkascan/polkascan-explorer-gui/10/100023469

### CODE REVIEW

**Comment by anldrms** [comment]
I saw right now another guy already complete this translation on Turkish. But there is any many empty field his json and some words are incorrect. Could you please compare it? @arjanz

**Comment by anldrms** [comment]
@emielvanderhoek

**Comment by anldrms** [comment]
@emielvanderhoek Can you please look into it?

**Comment by emielvanderhoek** [comment]
The Turkish translation we merged a while back looks good to me.

**Comment by anldrms** [comment]
Thanks anyway , good luck with your perfect translation.

**Pull request closed without merging**
