### PR TITLE
finished es.json translation

### PR DESCRIPTION
**Pull request by federicosan**
I still need to make some tests on the VM.

As a note, I need to state that I decided not to translate terms like Extrinsics or Referenda, there is a translation but I think of this terms as some sort of reserved keywords in a programming language, like a Personal Noun, they and I prefer not to translate this, this words encapsulate a concept and are better not being translated in my opinion. You can disagree and I can find a translation for these words, but I think it would be unwise to.

### CODE REVIEW

**Comment by emielvanderhoek** [comment]
Thank you for your efforts @federicosan 

Would you please be so kind to send me a signed Contributor License Agreement as mentioned in this issue #5  ? You can send that signed document to "emiel AT web3scan DOT eu". 

Additionally, Would you be so kind to include a written memo in the comments of this issue #5 or PR #30 that explains some choices you made with this translation. This is part of the required deliverables as mentioned in this issue.

> Written memo (in English) to explain why translated terms or transliterations were chosen for specific technical notions and terminology. Ideally this memo provides a reference to other places where similar translated terms or transliterations were chosen. I.e. how would the term extrinsic be translated?

You can check out some of the other completed translations to see how others have submitted these notes. (example: https://github.com/polkascan/polkascan-explorer-gui/pull/20)

Let me know if you have any questions.

**Comment by federicosan** [comment]
Hi @emielevanderhoek sure I will check on this and sign right away. The memo was this note stated above 

> As a note, I need to state that I decided not to translate terms like Extrinsics or Referenda, there is a translation but I think of this terms as some sort of reserved keywords in a programming language, like a Personal Noun, they and I prefer not to translate this, this words encapsulate a concept and are better not being translated in my opinion. You can disagree and I can find a translation for these words, but I think it would be unwise to.

I can extend on this as there are many things I noticed from the file, it would be a lot of work but I can do it for the sake of collaboration to annotate all the bits that are off on the keys. 

I will submit a new PR with some fixes I am currently making. Also, I want to state that the branch made for this was not working properly the networks would not appear to be selected, I had to work on the master to test it out.

**Comment by federicosan** [comment]
I will add a more detailed memo this week.

**Comment by emielvanderhoek** [comment]
Thank you @federicosan 
After we get the memo (as a comment in issue #5 ) we will evaluate and merge your PR.
Then we can go towards payout.

**Comment by federicosan** [comment]
**Memo**: When translating threshold, in Spanish there is not a clear definition as in English, many times umbral and límite are being used interchangeably, so I consulted other translators and checked some other places where the word threshold was being translated, I decided to change it from límite to umbral as in nutrition facts translations on every product.
Words like extrinsics or referenda were not translated, and doing so seemed like a bad desition, first, this has not yet been translated in the polkadot wiki, so any translation would need to be adjusted in the future when translations to the wiki appear, second it seemed like a novel concept exclusive to the polkadot network (I may be wrong) in comparison to other terms like validator and nominator that are seen in other blockchains like the bitcoin blockchain (checked some academic publications) 
Aye and Nay were not translated as the translations do not, in my opinion, express the true spirit of this old expression

>  The word aye (/aɪ/), as a synonym for yes in response to a question, dates to the 1570s and, according to the Online Etymology Dictionary, is of unknown origin; it may derive as a variation of the word I (in the context of "I assent"); as an alteration of the Middle English yai ("yes"), or from the adverb aye (meaning always "always, ever"), which derives from the Old Norse ei.[50] Use of aye is an archaism in most of the English-speaking world but remains in use in Scottish and Northern English usage.[51]

**Comment by emielvanderhoek** [comment]
@arjanz would you merge and activate the Spanish language through this PR, please?

**Pull request merged**
