### PR TITLE
Japanese Localization ja.json

### LINKED ISSUE #3: Polkascan internationalization: Japanese translation
# Polkascan internationalization: Japanese translation

## About Polkascan OS (for Polkadot Runtime Environments)
Polkascan OS provides an open-source block explorer for any Substrate-based blockchain. Polkascan OS consists of a number of distinct software artifacts which collectively orchestrate Polkascan. The Harvester transforms a Substrate node’s raw data into relational data, with the help of Substrate Interface Library and the SCALE Codec Library. The produced relational data is disseminated by the Explorer API and in turn made accessible to end-users by the Explorer GUI. We have chosen to provide full Docker support for all our artifacts, hence all our repositories have Dockerfiles in their root. All these open-source software artifacts and many others can be found in the Polkascan organization on GitHub (https://github.com/polkascan).

## Internationalization of Polkascan OS Explorer GUI
The Polkascan OS Explorer GUI (https://github.com/polkascan/polkascan-pre-explorer-gui) is an Angular application. Previous work has implemented internationalization & localization standards for the Angular application. Currently the application supports the English and Chinese languages.

## Additional translations of Polkascan OS Explorer GUI
This issue specifies a request to extend the Angular application with additional languages. This in turn will make Polkascan OS available and user-friendly to a worldwide audience in multiple languages and with multiple localization settings.

afbeelding

## Deliverables
- Japanese translation for the Angular application.
- Use our feature branch: 'https://github.com/polkascan/polkascan-explorer-gui/tree/feature/i18n'
- Modifications of the Japanese language-pack: https://github.com/polkascan/polkascan-explorer-gui/blob/feature/i18n/src/assets/i18n/ja.json
- Please note that some values have already been set in the Japanese language-pack. These are machine translations and very likely require modification and thorough review.
- Written memo (in English) to explain why translated terms or transliterations were chosen for specific technical notions and terminology. Ideally this memo provides a reference to other places where similar translated terms or transliterations were chosen. I.e. how would the term `extrinsic` be translated?

## Skills
- Japanese language native.
- Conceptual understanding of Blockchain, Polkadot and Substrate.
- Capable of translation or transliteration of technical notions and terminology.
- Our preference goes to a current Polkadot Ambassador.

## Requirements for work to be approved
- Pull request to https://github.com/polkascan/polkascan-explorer-gui/tree/feature/i18n
- Signed contributor license agreement with WEB3SCAN (download and sign: 
[Contributor License Agreement v1.0.0.pdf](https://github.com/polkascan/polkascan-explorer-gui/files/4288058/Contributor.License.Agreement.v1.0.0.pdf)
- Meet expectations of deliverables

## Getting started with Docker
```
git clone https://github.com/polkascan/polkascan-explorer-gui.git
cd polkascan-explorer-gui
git checkout feature/i18n
docker build -t polkascan-explorer-gui:latest .
docker run --rm -p 8000:80 --mount type=bind,source="$(pwd)"/src/assets/i18n,target=/usr/share/nginx/html/assets/i18n polkascan-explorer-gui:latest
```
Run in a browser (e.g. Firefox): http://127.0.0.1:8000
- Select the Japanese language on the top-right side of the screen.
- Make modifications in the Japanese language pack (`src\assets\i18n\ja.json`)
- Refresh in browser to check modifications

## Cleanup Docker
use with caution
```
# remove unused docker images
docker system prune
# stop & remove all docker containers
docker system prune -a
# remove docker volumes
docker volume prune
```

### PR DESCRIPTION
**Pull request by Graceslsne8**
Close #3

### CODE REVIEW

**Comment by Graceslsne8** [comment]
@emielvanderhoek 
I have finished the translation! Please check and merge.

**Comment by emielvanderhoek** [comment]
Thank you for your efforts @Graceslsne8 
Would you please be so kind to send me a signed Contributor License Agreement as mentioned in the original issue here: #3  ? You can send that signed document to "emiel AT web3scan DOT eu".

After that I'll ask to get this merged and we can go towards bounty payout.

**Comment by emielvanderhoek** [comment]
Additionally, Would you be so kind to include a written memo in the comments of this issue or PR #27 that explains some choices you made with this translation. This is part of the required deliverables as mentioned in issue #3 

> Written memo (in English) to explain why translated terms or transliterations were chosen for specific technical notions and terminology. Ideally this memo provides a reference to other places where similar translated terms or transliterations were chosen. I.e. how would the term extrinsic be translated?

You can check out some of the other completed translations to see how others have submitted these notes. (example: https://github.com/polkascan/polkascan-explorer-gui/pull/20)

Let me know if you have any questions.

**Comment by Graceslsne8** [comment]
- Governance related terms such as election activity（選挙活動）, treasury （ 基金）, candidacy（立候補）, nominate（推薦）, proposal（提案）, referenda（投票）were translated into Japanese governmental vocabularies to make it more relatable and easier to understand the system. 

-Finance related terms are translated into financial vocabularies that are commonly used in the Japanese blockchain/cryptocurrency sphere. 

- Some words such as "Riot" and "Sudo" are not translated as they would be better understood in English and translating it into Japanese would create misunderstanding/misinterpretation. 

- "Extrinsic" is left untranslated because making it Japanese could change the meaning of the original term and it is well understood among the Japanese developers.

**Comment by emielvanderhoek** [comment]
> Thank you for your efforts @Graceslsne8
> Would you please be so kind to send me a signed Contributor License Agreement as mentioned in the original issue here: #3 ? You can send that signed document to "emiel AT web3scan DOT eu".
> After that I'll ask to get this merged and we can go towards bounty payout.

Please send us the Signed Contributor License Agreement and we can merge this PR and go towards payout. Thank you in advance.

**Comment by Graceslsne8** [comment]
@emielvanderhoek 
Hey there. I have already sent you the Agreement earlier today.
Let me know if you have gotten it or not.

**Comment by emielvanderhoek** [comment]
@Graceslsne8 we received a document but it was not a signed document. Please send us a signed CLA.

**Comment by Graceslsne8** [comment]
@emielvanderhoek 
My apologies.
I have sent you a signed one.

**Comment by emielvanderhoek** [comment]
> I have sent you a signed one.

@Graceslsne8 : Received thank you. Everything looks good. We will merge this PR later this week. That will trigger the payout procedure.

@arjanz : looks good to me. Please merge this PR at your convenience and activate the Japanese language pack.

**Pull request merged**
